### ISSUE TITLE
openscad-mdimggen wishlist

### ISSUE THREAD

**Issue by RAMilewski** [BelfrySCAD/openscad_docsgen#24]
There appears to be no mdimggen-specific documentation.  It seems to work similarly to docsgen  Example & Figures blocks, but not exactly.

The following changes would make writing BOSL2 Tutorials easier:

- [x] VPD, VPT, and VPR entries in the metadata list are added as visible scad lines in the rendered code.  They should be invisible.
- [x] VPD overrides 2D and forces a 3D image.
- [x] Lines in the example script that begin with -- throw an error rather than the Example block behavior of executing but not appearing in the rendered scripts.
- [x] NoScales is not listed in the Example Block directives list, but it does suppress the axis scales in the image.
- [x] The Figures Block directives list includes an FPS directive that does not appear in the Example Block directives list and does not work in mdimggen.

The remainder of the directives in the Example Block directives list appear to work in openscad-mdimggen.

**Comment by revarbat** [comment]
Implemented in v2.0.43
