### ISSUE TITLE
distutils removed from Python3.12

### ISSUE THREAD

**Issue by RAMilewski** [BelfrySCAD/openscad_docsgen#25]
openscad-docsgen requires distutils which has been removed from Python3.12

Workaround:     pip3 install setuptools

setuptools includes the deprecated distutils.

**Comment by pinkfish** [comment]
Getting this as well: ModuleNotFoundError: No module named 'distutils'

**Comment by revarbat** [comment]
If I'm understanding the issue correctly, it appears this bug is actually in https://github.com/BelfrySCAD/openscad_mdimggen

**Comment by revarbat** [comment]
I've removed the distutils dependency from openscad_runner.
